"""
fig13_eprc_tuning.py - Figure 13 ePRC Parameter Sweeps.

Sweeps target biophysical parameters (synaptic decay tau_decay linearly and A-type conductance g_a logarithmically)
and computes ePRC curves for each parameter value across 10 autogenerated samples.

Export CSVs:
- plotdata/plotdata_eprc_sweep_exc_synapse_nom_tau_decay.csv (Wide format for TikZ)
- plotdata/plotdata_eprc_sweep_exc_neuron_g_a.csv (Wide format for TikZ)
- results/data/fig13_eprc_tuning_data.csv (Long format for analysis)
"""

from __future__ import annotations

import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from src.eprc_engine import compute_eprc_curve
from src.helper import export_to_csv

# Paths
DATA_DIR     = PROJECT_ROOT / "results" / "data"
PLOTDATA_DIR = PROJECT_ROOT / "plotdata"
OUTPUT_FIG   = PROJECT_ROOT / "results" / "figures" / "fig13_eprc_tuning.png"

# Configuration
DT = 0.001
SPIKE_THRESHOLD = 50.0
IMPULSE_WIDTH = 0.1
IMPULSE_AMPLITUDE = 100.0
INPUT_PERIOD = 50.0
SINGLE_EVENT = True
T_NOM_START = 50.0
DURATION_MULTIPLIER = 6.0
MIN_T = 350.0
SYN_TYPE = "exc"

TP_VALUES = np.arange(-50.0, 100.5, 0.2)


def run_sweep(param_name: str, param_values: list[float] | np.ndarray, base_overrides: dict) -> pd.DataFrame:
    records = []
    for val in param_values:
        overrides = base_overrides.copy()
        overrides[param_name] = float(val)

        samples = compute_eprc_curve(
            tp_values=TP_VALUES,
            input_period=INPUT_PERIOD,
            dt=DT,
            impulse_width=IMPULSE_WIDTH,
            impulse_amplitude=IMPULSE_AMPLITUDE,
            spike_threshold=SPIKE_THRESHOLD,
            single_event=SINGLE_EVENT,
            duration_multiplier=DURATION_MULTIPLIER,
            min_t=MIN_T,
            t_nom_start=T_NOM_START,
            parallelize=True,
            param_overrides=overrides,
            syn_type=SYN_TYPE,
        )

        for s in samples:
            if s.is_valid and s.delta_t is not None:
                records.append({
                    "param_name": param_name,
                    "param_value": float(val),
                    "tp": s.tp,
                    "delta_t": s.delta_t
                })

    return pd.DataFrame(records)


def run():
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    PLOTDATA_DIR.mkdir(parents=True, exist_ok=True)

    # 10 samples: tau_values linear between 3.0 and 21.5
    tau_values = np.linspace(3.0, 21.5, 10)
    
    # 10 samples: ga_values logspace between 0.0 and 1.5
    t = np.linspace(0, 1, 10)
    ga_values = 1.5 * np.log10(1 + 9 * t) 

    # Sweeps (Long Format)
    df_tau = run_sweep("synapse_nom.tau_decay", tau_values, {"synapse_sens.g_max": 0.05, "neuron.g_a": 0.0})
    df_ga  = run_sweep("neuron.g_a", ga_values, {"synapse_sens.g_max": 0.05})
    df_combined = pd.concat([df_tau, df_ga], ignore_index=True)

    # Export Long Format for analysis
    export_to_csv(df_tau, DATA_DIR / "plotdata_eprc_sweep_exc_synapse_nom_tau_decay.csv")
    export_to_csv(df_ga, DATA_DIR / "plotdata_eprc_sweep_exc_neuron_g_a.csv")
    export_to_csv(df_combined, DATA_DIR / "fig13_eprc_tuning_data.csv")
    
    # -------------------------------------------------------------------------
    # Create "Wide" Format versions for LaTeX/TikZ plotting
    # -------------------------------------------------------------------------
    # Pivot so 'tp' is the index, and each parameter value becomes its own column
    df_tau_wide = df_tau.pivot(index="tp", columns="param_value", values="delta_t").reset_index()
    df_ga_wide = df_ga.pivot(index="tp", columns="param_value", values="delta_t").reset_index()
    
    # Rename the parameter columns to val_0, val_1, ... val_9 for easy looping in TikZ
    df_tau_wide.columns = ["tp"] + [f"val_{i}" for i in range(len(df_tau_wide.columns) - 1)]
    df_ga_wide.columns = ["tp"] + [f"val_{i}" for i in range(len(df_ga_wide.columns) - 1)]

    # Export Wide Format exclusively for TikZ
    export_to_csv(df_tau_wide, PLOTDATA_DIR / "plotdata_eprc_sweep_exc_synapse_nom_tau_decay.csv")
    export_to_csv(df_ga_wide, PLOTDATA_DIR / "plotdata_eprc_sweep_exc_neuron_g_a.csv")
    
    print(f"[fig13] Exported ePRC sweep CSVs to DATA_DIR (long) and PLOTDATA_DIR (wide)")

    # Plot (Matplotlib)
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11, 4.5), dpi=150)
    colors1 = plt.cm.viridis(np.linspace(0, 1, len(tau_values)))
    colors2 = plt.cm.plasma(np.linspace(0, 1, len(ga_values)))

    if not df_tau.empty:
        for idx, (val, grp) in enumerate(df_tau.groupby("param_value", sort=False)):
            ax1.plot(grp["tp"], grp["delta_t"], label=rf"$\tau_{{decay}}={val:.1f}$", color=colors1[idx % len(colors1)], lw=1.5)
    ax1.set_title(r"ePRC Sweep: Synaptic Decay ($\tau_{\mathrm{decay}}$)", fontsize=11, fontweight="bold")
    ax1.set_xlabel(r"Perturbation Delay $t_p$ (ms)", fontsize=10)
    ax1.set_ylabel(r"Spike Shift $\Delta t$ (ms)", fontsize=10)
    ax1.legend(loc="upper right", fontsize=7, ncol=2)
    ax1.grid(True, linestyle="--", alpha=0.5)

    if not df_ga.empty:
        for idx, (val, grp) in enumerate(df_ga.groupby("param_value", sort=False)):
            ax2.plot(grp["tp"], grp["delta_t"], label=rf"$g_a={val:.2f}$", color=colors2[idx % len(colors2)], lw=1.5)
    ax2.set_title(r"ePRC Sweep: Conductance ($g_a$ inverse exponentially spaced)", fontsize=11, fontweight="bold")
    ax2.set_xlabel(r"Perturbation Delay $t_p$ (ms)", fontsize=10)
    ax2.set_ylabel(r"Spike Shift $\Delta t$ (ms)", fontsize=10)
    ax2.legend(loc="upper right", fontsize=7, ncol=2)
    ax2.grid(True, linestyle="--", alpha=0.5)

    plt.tight_layout()
    OUTPUT_FIG.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUTPUT_FIG)
    plt.close(fig)
    print(f"[fig13] Wrote figure to: {OUTPUT_FIG}")


if __name__ == "__main__":
    run()